CREATE TABLE [Addresses] (
    [Id] bigint NOT NULL IDENTITY,
    [AddressFormatId] bigint NULL,
    [BuildingName] nvarchar(max) NULL,
    [StreetAddress] nvarchar(100) NOT NULL,
    [AdditionalStreetAddress] nvarchar(100) NULL,
    [Suburb] nvarchar(50) NULL,
    [TownOrCity] nvarchar(50) NULL,
    [PostCode] nvarchar(15) NULL,
    [CountryId] bigint NULL,
    [IsProtected] bit NOT NULL,
    [IsPermanent] bit NOT NULL,
    [EffectiveFrom] nvarchar(8) NULL,
    [EffectiveTo] nvarchar(8) NULL,
    [DomicileId] bigint NULL,
    [IsPrimary] bit NOT NULL,
    [AddressTypeId] bigint NULL,
    [PatientId] bigint NULL,
    CONSTRAINT [PK_Addresses] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Addresses_AddressFormats_AddressFormatId] FOREIGN KEY ([AddressFormatId]) REFERENCES [AddressFormats] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Addresses_AddressTypes_AddressTypeId] FOREIGN KEY ([AddressTypeId]) REFERENCES [AddressTypes] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Addresses_Countries_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [Countries] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Addresses_Domiciles_DomicileId] FOREIGN KEY ([DomicileId]) REFERENCES [Domiciles] ([Id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Addresses_Patients_PatientId] FOREIGN KEY ([PatientId]) REFERENCES [Patients] ([Id]) ON DELETE CASCADE
)
