AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ProjectName:
    Type: String
    Default: PatientDemographicService
  Environment:
    Type: String
    Default: sandbox
Resources:
  PatientDemographicUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: !Sub '${ProjectName}-${Environment}-UserPool'
      UsernameConfiguration:
        CaseSensitive: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
          Mutable: true
    DeletionPolicy: Delete
  PatientDemographicDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref PatientDemographicUserPool
      Domain: mhip-patient-demographic-userpool-sandbox
  PatientDemographicResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
      UserPoolId: !Ref PatientDemographicUserPool
      Identifier: PatientDemographicServiceAPI
      Name: PatientDemographicServiceAPI
      Scopes:
        - ScopeName: api.read
          ScopeDescription: 'Access read operations'
        - ScopeName: api.write
          ScopeDescription: 'Access write operations'