AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation template to create RDS DBInstance."
Parameters:
  DbIdentifierName:
    Type: String
    Default: patientdemographic-d-database
  DbUsername: 
    Type: String
    Default: sa
  DbPassword:
    Type: String
    Default: Password.1
  DbSubnetGroup:
    Type: String
    Default: patient-demographic-d-rds-subnetgroup
  DbVPCSecurityGroups:
    Type: CommaDelimitedList
    Default: sg-04615d2f0df19bb91
  ParamStoreKMSMasterKeyIdARN: 
    Type: AWS::SSM::Parameter::Value<String>
    Default: /PatientDemographicService/sandbox/CloudFormation/KMS-Master-KeyIdARN
Resources:
  PatientDemographicDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: !Ref DbIdentifierName
      DBInstanceClass: db.t3.small
      DBSubnetGroupName: !Ref DbSubnetGroup
      Engine: sqlserver-web
      EngineVersion: 15.00.4153.1.v1
      KmsKeyId: !Ref ParamStoreKMSMasterKeyIdARN
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups: !Ref DbVPCSecurityGroups


