name: Patient demographic service CI/CD pipeline

on:
  push:
    branches: 
      - feature/*
      
  workflow_dispatch:

env:
  NETCORE_VERSION: '3.1.x'
  PROJECT_NAME: 'MessageProcessorLambda'
  
jobs:

  build-MessageProcessorLambda-sandbox:
    if: startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push'
    
    runs-on: ubuntu-latest

     env:
      ENVIRONMENT_NAME: sandbox
      AWS_S3_BUCKET: patient-demographic-service-sandbox-s3
      AWS_STACKNAME: patient-demographic-service-sandbox-stack

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --output "./src/MessageProcessorLambda/bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
    
    - name: Create directory `dist`
      run: mkdir -p ./dist

    - name: zip-files
      uses: papeloto/action-zip@v1
      with:
        files: ./src/MessageProcessorLambda/bin/Release/netcoreapp3.1/publish/
        dest: ./dist/${{env.PROJECT_NAME}}-${{env.ENVIRONMENT_NAME}}-${{github.run_number}}.zip

    - name: Configure AWS credentials from sandbox account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.SANDBOX_AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.SANDBOX_AWS_SECRET_KEY}}
        aws-session-token: ${{secrets.SANDBOX_AWS_SESSION_TOKEN}}
        aws-region: ap-southeast-2
    
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: apigateway-sqs-stack
        template: "./cloudformation/message-infra-cfn.yml"
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          BucketName=${{env.AWS_S3_BUCKET}},
          CodeKey=${{env.PROJECT_NAME}}-${{env.ENVIRONMENT_NAME}}-${{github.run_number}}.zip
        capabilities: "CAPABILITY_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND"

