name: Patient demographic service CI/CD pipeline

on:
  push:
    branches: 
      - develop
      - feature/*
      
  workflow_dispatch:

env:
  NETCORE_VERSION: '3.1.x'
  
jobs:

  build-PatientServiceApi-sandbox:
    if: startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push'
    
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: PatientServiceWebApi
      ENVIRONMENT_NAME: sandbox
      AWS_S3_BUCKET: patient-demographic-service-sandbox-s3
      AWS_STACKNAME: patient-demographic-service-sandbox-stack

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --output "./src/PatientService.WebAPI/bin/Release/netcoreapp3.1/publish" --configuration "Release" --framework "netcoreapp3.1" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
      
      - name: Create directory `dist`
        run: mkdir -p ./dist
